ssu_cp : ssu_cp.o copy.o option.o 
	gcc -o ssu_cp ssu_cp.o copy.o option.o
ssu_cp.o : ssu_cp.c
	gcc -c -o ssu_cp.o ssu_cp.c
copy.o : copy.c 
	gcc -c -o copy.o copy.c
option.o : option.c
	gcc -c -o option.o option.c
